### ISSUE TITLE
File not downloading (large file)

### ISSUE THREAD

**Issue by utopeeuh** [keotl/invert-pdf#15]
It says "Failed - Network error" every time I try to download.
My pdf is 170 pages, 3.3 mb, which I assume is considered large.
I saw a similar issue where you said you put a limit that might send a random error if I'm not mistaken. Should I keep reuploading till it works (given the size) or should I split the pdf instead (if so, what would be your limit per pdf)? Thanks

**Comment by keotl** [comment]
Hi, the current implementation rasterizes each page individually, so even though your file is only 3.3 MB, the large number of pages is likely what is causing the timeout issue. You can try reducing the quality setting or splitting your file into smaller chunks.

I will close this issue for now and track performance optimizations in #16. Feel free to re-open if you experience other issues.

Cheers!
