### ISSUE TITLE
Need to increase resolution of the resulting pdf

### ISSUE THREAD

**Issue by kevinwkc** [keotl/invert-pdf#9]
Great App you building.
Need to increase resolution of the resulting pdf
right now it is very hard to see
example
![image](https://user-images.githubusercontent.com/11415653/81626731-8ad34580-93ca-11ea-8163-f19d02247040.png)

Please help, Thank You

**Comment by AlbertoCentonze** [comment]
Yeah, I agree. Isn't possible to invert colours while keeping the pdf vectorial? I guess it would take a lot of work but still looks doable.

**Comment by keotl** [comment]
I have not looked deeply into this, but I think keeping the PDF vectorial would be very difficult and most likely require purely custom processing (more than the ImageMagick or ghostscript libraries can provide.) If you have pointers in that regard, I would be happy to hear them!

In the meantime, I propose adding a DPI slider on the UI as an advanced option.

**Comment by keotl** [comment]
Status Update: I added a quality options dropdown on the UI. Closing for now.

**Comment by AlbertoCentonze** [comment]
Awesome, thanks a lot!
